spring:
  application:
    name: movie-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379

server:
  port: 8888
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true


#Dubbo??
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.movie.front
  consumer:
    check: false
    timeout: 50000
    retries: 0
  application:
    id: dubbo-provider
    name: dubbo-provider

#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: uuid
#      #schema: classpath:/sql/schema.sql
#  type-aliases-package: com.movie.api.model.entity